name: CI tests

on: [push]

jobs:
  linux:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install clingo
        shell: bash -l {0}
        run: |
          conda install -c potassco clingo=5.5.0
          conda install -c potassco clingo-dl=1.2.0
      - name: Build
        run: |
          export CLINGO_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo build --features=derive,dl-theory --verbose
      - name: Run tests
        run: |
          export CLINGO_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export LD_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo test --features=derive,dl-theory --verbose
  macos:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install clingo
        shell: bash -l {0}
        run: |
          conda install -c potassco clingo=5.5.0
          conda install -c potassco clingo-dl=1.2.0
      - name: Build
        run: |
          export CLINGO_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          cargo build --features=derive,dl-theory --verbose
      - name: Run tests
        run: |
          export CLINGO_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          export DYLD_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          cargo test --features=derive,dl-theory --verbose
  windows:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install clingo
        run: |
          conda install -c potassco clingo=5.5.0
          conda install -c potassco clingo-dl=1.2.0
      - name: Build
        env:
          CLINGO_LIBRARY_PATH: C:\Miniconda\envs\test\Library\lib
          CLINGO_DL_LIBRARY_PATH: C:\Miniconda\envs\test\Lib
        run: |
          cargo build --features=derive,dl-theory --verbose
      - name: Run tests
        env:
          CLINGO_LIBRARY_PATH: C:\Miniconda\envs\test\Library\lib
          CLINGO_DL_LIBRARY_PATH: C:\Miniconda\envs\test\Lib
          LD_LIBRARY_PATH: C:\Miniconda\envs\test\Library\lib;C:\Miniconda\envs\test\Lib
        run: |
          cargo test --features=derive,dl-theory --verbose
  linux-static:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install bison
        run: sudo apt-get install bison
      - name: Install re2c
        run: sudo apt-get install re2c
      - name: Build
        run: cargo build --features=static-linking,derive --verbose
      - name: Run tests
        run: cargo test --features=static-linking,derive --verbose
  macos-static:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: |
          brew update
          brew install bison@2.7
          brew install re2c
      - name: Build
        run: |
          export PATH="/usr/local/opt/bison@2.7/bin:$PATH"
          cargo build --features=static-linking,derive --verbose
      - name: Run tests
        run: |
          export PATH="/usr/local/opt/bison@2.7/bin:$PATH"
          cargo test --features=static-linking,derive --verbose
  windows-static:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install bison
        run: choco install winflexbison
      - name: Install re2c
        run: choco install re2c
      - name: Build
        run: cargo build --features static-linking,derive -vv
      - name: Run tests
        run: cargo test --features static-linking,derive --verbose
